### ISSUE TITLE
1920x1080

### ISSUE THREAD

**Issue by zombodotcom** [Australix/PoeInvSort#2]
Could you help me out with the Opentab for 1920x1080 resolution? I am getting close with the x and y values but I was just wondering if you had a 1920x1080 already.

Also for the settings.txt file I think it would be better to have it read a file outside of the jar in the same directory, I think people would like the option of on the fly setting changing instead of having to recompile the jar. I just changed your file read in part to just read in the settings file from the directory

**Comment by Australix** [comment]
Hi zombo, sorry for the late response. Did not expect anyone to be looking at this :)

Unfortunately I dont, as I play windowed at 1440p. In my program I scale all coordinates by the total height of the window (PoE UI size is based only on height), and then scale everything again because JNA mouse movement scales the monitor from 0-65535 x and y for whatever reason. 

I recommend just taking screencaps in windowed fullscreen and using MSpaint to get the exact coordinates :) that's what I did.

You may be right. Something I will consider when I update this program next time. You can open the jar with winrar or something similar and edit the TXT file directly, which I thought was accessible enough.

**Comment by zombodotcom** [comment]
I almost started using post it notes and increments! Thank you again for the cool thing you created, I have learned a lot more already because of this program you put together ♥️

**Comment by zombodotcom** [comment]
I already implemented the text file version on my own at home but I've been gone on vacation for a few weeks. I just made it grab the file in the directory than inside the resources folder. Lol dang I forgot jar files could be opened like a zip 😂

**Comment by Australix** [comment]
No problem! Its very encouraging to know I may have helped someone with their own project! Hope it also prevents some wrist RSI :)

 If you don't mind me asking, does the program work well for you? I have only tested it on my computer. My main concerns are if the buttons are clicked accurately, and if it is too fast and misses some items. I know that there is currently a bug with the Timeless eternal empire splinter and an uncommon crash where the program stops halfway through.

**Comment by zombodotcom** [comment]
Hmm weird, I haven't experienced any issues. I just added time in between each click to be 1 second so I don't accidently get flagged for botting. Not that I think this would because it's not making you any better at the game, just saving my wrists.

Didn't notice any errors when I had the time to click the same as original

**Comment by Australix** [comment]
Thats great to hear. Thanks for the info!
